# Generated by Django 4.1.2 on 2024-04-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_alanine_nutrition_cholesterol_mg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='niacin_mg',
            new_name='niac_mg',
        ),
    ]
