# Generated by Django 4.1.2 on 2024-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
    ]
